apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: system

  source:
    chart: sealed-secrets
    helm:
      parameters:
        - name: namespace
          value: kube-system
    repoURL: "https://kubernetes-charts.storage.googleapis.com/"
    targetRevision: "1.*"

  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      selfHeal: true
