---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: traefik
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik

spec:
  helmVersion: v3
  targetNamespace: traefik
  releaseName: traefik
  chart:
    repository: https://containous.github.io/traefik-helm-chart/
    name: traefik
    version: 8.9.1
  values:
    service:
      annotations:
        # https://www.linode.com/docs/kubernetes/deploy-nodebalancers-with-linode-ccm/#annotations
        "service.beta.kubernetes.io/linode-loadbalancer-protocol": "tcp"
    ingressRoute:
      dashboard:
        labels:
          "app.kubernetes.io/name": "traefik"
    env:
      - name: "LINODE_TOKEN"
        valueFrom:
          secretKeyRef:
            name: traefik-linode-dns
            key: token
    deployment:
      initContainers:
        # The "volume-permissions" init container is required if you run into
        # permission issues. Related issue:
        # https://github.com/containous/traefik/issues/6972
        - name: volume-permissions
          image: busybox:1.32.0
          command: ["/bin/sh", "-c", "/bin/chmod -Rv 0600 /data/*"]
          volumeMounts:
            - name: data
              mountPath: /data
    additionalArguments:
      - "--log.level=INFO"
      - "--entrypoints.websecure.http.tls.certResolver=le"
      - "--entrypoints.websecure.http.tls.domains[0].main=docwhat.net"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.docwhat.net"
      - "--certificatesresolvers.le.acme.email=docwhat@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=linodev4"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    persistence:
      enabled: true
      annotations:
        "pv.beta.kubernetes.io/gid": "65532"
      size: 1Gi
    securityContext:
      readOnlyRootFilesystem: false
    podSecurityContext:
      fsGroup: 65532
    # https://github.com/containous/traefik-helm-chart/pull/212
