---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: traefik
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik

spec:
  helmVersion: v3
  targetNamespace: traefik
  releaseName: traefik
  chart:
    repository: https://containous.github.io/traefik-helm-chart/
    name: traefik
    version: 8.12.0
  values:
    service:
      enabled: false
    ingressRoute:
      dashboard:
        labels:
          "app.kubernetes.io/name": "traefik"
    env:
      - name: "LINODE_TOKEN"
        valueFrom:
          secretKeyRef:
            name: traefik-linode-dns
            key: token
    additionalArguments:
      - "--log.level=INFO"
      - "--entrypoints.websecure.http.tls.certResolver=le"
      - "--entrypoints.websecure.http.tls.domains[0].main=docwhat.org"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.docwhat.org"
      - "--entrypoints.websecure.http.tls.domains[1].main=docwhat.net"
      - "--entrypoints.websecure.http.tls.domains[1].sans=*.docwhat.net"
      - "--entrypoints.websecure.http.tls.domains[2].main=docwhat.dev"
      - "--entrypoints.websecure.http.tls.domains[2].sans=*.docwhat.dev"
      - "--certificatesresolvers.le.acme.email=docwhat@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=linodev4"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--metrics.prometheus"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--entrypoints.metrics.address=:8082"

    persistence:
      enabled: true
      existingClaim: traefik-claim
    deployment:
      initContainers:
        # The "volume-permissions" init container is required if you run into
        # permission issues. Related issue:
        # https://github.com/containous/traefik/issues/6972
        - name: volume-permissions
          image: busybox:1.32.0
          command: ["/bin/sh", "-c", "/bin/chmod -Rv 0600 /data/*.json"]
          volumeMounts:
            - name: data
              mountPath: /data

    podSecurityContext:
      fsGroup: 65532
    # https://github.com/containous/traefik-helm-chart/pull/212
