---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: "grafana"
  namespace: "metrics"
spec:
  helmVersion: "v3"
  releaseName: "grafana"
  targetNamespace: "metrics"
  chart:
    name: "grafana"
    version: "5.5.0"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  values:
    env:
      GF_SERVER_ROOT_URL: "https://grafana.docwhat.net"
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_GITHUB_ENABLED: true
      GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: holtje
    envFromSecret: "grafana-ini-secrets"
