apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
  namespace: metrics
  labels:
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: grafana
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage
