---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: "prom-oper-chart"
  namespace: "metrics"
spec:
  helmVersion: "v3"
  targetNamespace: "metrics"
  releaseName: "prometheus-operator"
  chart:
    name: "prometheus-operator"
    version: "9.2.1"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  values:
    defaultRules:
      rules:
        general: false

    # Can't monitor linode control plane.
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false

    grafana:
      persistence:
        enabled: true
        existingClaim: grafana-claim
      admin:
        existingSecret: "grafana-env-secrets"
        userKey: "GF_SECURITY_ADMIN_USER"
        passwordKey: "GF_SECURITY_ADMIN_PASSWORD"
      env:
        GF_AUTH_ANONYMOUS_ENABLED: false
        GF_AUTH_BASIC_ENABLED: false
        GF_AUTH_DISABLE_LOGIN_FORM: true
        GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: holtje
        GF_AUTH_GITHUB_ENABLED: true
        GF_AUTH_OAUTH_AUTO_LOGIN: true
        GF_SERVER_ROOT_URL: "https://grafana.docwhat.net/"
        GF_SERVER_ENABLE_GZIP: true
      envFromSecret: "grafana-env-secrets"
    prometheus:
      prometheusSpec:
        externalUrl: "https://prometheus.docwhat.net/"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: linode-block-storage
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      alertmanagerSpec:
        externalUrl: https://alertmanager.docwhat.net/
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: linode-block-storage
              resources:
                requests:
                  storage: 10Gi
