---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: "prom-oper-chart"
  namespace: "metrics"
spec:
  helmVersion: "v3"
  targetNamespace: "metrics"
  releaseName: "prometheus-operator"
  chart:
    name: "prometheus-operator"
    version: "9.2.1"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  values:
    kubeEtcd:
      enabled: false
