---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
  namespace: demo
  labels:
    app: demo-site
  annotations:
    fluxcd.io/tag.demo-site: semver:~3
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-site
  template:
    metadata:
      labels:
        app: demo-site
    spec:
      containers:
      - name: site
        image: stefanprodan/podinfo:4.0.6
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "250m"
            memory: "32Mi"
        ports:
        - containerPort: 9898
