---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  namespace: demo
  labels:
    app: demo-site
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9898
  selector:
    app: demo-site
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: site-route
  namespace: demo
  labels:
    app: demo-site
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`site.localhost`)
      services:
        - name: site-service
          port: 80
