apiVersion: v1
kind: Service
metadata:
  name: site-service
  namespace: demo
  labels:
    app: demo-site
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9898
  selector:
    app: demo-site
