---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: e1b1cc32e02deb06426e
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: holtje
  repositories: |
    - name: bitnami
      type: helm
      url: https://charts.bitnami.com/bitnami
    - name: prometheus-community
      type: helm
      url: https://prometheus-community.github.io/helm-charts
    - name: sealed-secrets
      type: helm
      url: https://bitnami-labs.github.io/sealed-secrets
    - type: git
      url: git@github.com:holtje/hive-config.git
      sshPrivateKeySecret:
        name: argocd-secret
        key: github.holtje.hive-config
    - type: git
      url: git@github.com:docwhat/vacation-calendar.git
      sshPrivateKeySecret:
        name: argocd-secret
        key: github.docwhat.vacation-planner
  statusbadge.enabled: "true"
  url: https://argocd.docwhat.net
