---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-import
  namespace: next
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-import
      environment: next
  template:
    metadata:
      labels:
        environment: next
        app: go-import
    spec:
      containers:
        - name: go-import
          image: docker.io/docwhat/go-importd:v1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "20m"
              memory: "8Mi"
          env:
            - name: "GO_IMPORTD_GITHUB_USER_URL"
              value: "https://github.com/docwhat"
            - name: "GO_IMPORTD_IMPORT_DOMAIN"
              value: "docwhat.org"
          ports:
            - containerPort: 80
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: go-import
  namespace: next
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: go-import
    environment: next
