---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-cleaning
  namespace: next
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: street-cleaning
      environment: next
  template:
    metadata:
      labels:
        environment: next
        app: street-cleaning
    spec:
      containers:
        - name: street-cleaning
          image: docker.io/docwhat/street_cleaning:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "20m"
              memory: "16Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /run
              name: run-volume
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: street-cleaning
  namespace: next
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: street-cleaning
    environment: next
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: street-cleaning-path
  namespace: next
spec:
  replacePath:
    path: "/"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: street-cleaning
  namespace: next

spec:
  entryPoints:
    - web
    - websecure

  routes:
    - match: "Host(`next.docwhat.net`) && Path(`/street-cleaning{?:.ics|}`)"
      kind: Rule
      services:
        - name: street-cleaning
          port: 80
      middlewares:
        - name: https-redirect
          namespace: traefik
        - name: street-cleaning-path
