---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-production
  namespace: docwhat
spec:
  selector:
    matchLabels:
      app: blog
      environment: production
  template:
    metadata:
      labels:
        environment: production
        app: blog
    spec:
      containers:
        - name: blog
          image: ghcr.io/docwhat/blog:sha-83d5d254
          resources:
            requests:
              # cpu: "0.5m"
              memory: "8Mi"
            limits:
              memory: "32Mi"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /run
              name: run-volume
          securityContext:
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: github-docker-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: blog-production
  namespace: docwhat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-production
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
    # - type: Resource
    #   resource:
    #     name: cpu
    #     targetAverageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: blog-production
  namespace: docwhat
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: blog
    environment: production
