---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-stg
  namespace: blog-stg
  labels:
    app: blog-stg
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-stg
  template:
    metadata:
      labels:
        app: blog-stg
    spec:
      containers:
        - name: blog
          image: docwhat/docwhat:master
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "200m"
              memory: "32Mi"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blog-stg
  namespace: blog-stg
  labels:
    app: blog-stg
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: blog-stg

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog-stg
  namespace: blog-stg
  labels:
    app: blog-stg
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`next.docwhat.net`)
      services:
        - name: blog-stg
          port: 80
