---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  helmVersion: v3
  targetNamespace: kube-system
  releaseName: metrics-server
  chart:
    name: metric-server
    version: "4.2.1"
    repository: "https://charts.bitnami.com/bitnami"
  values: {}
