---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  helmVersion: v3
  targetNamespace: kube-system
  releaseName: sealed-secrets
  chart:
    name: sealed-secrets
    version: "1.10.3"
    repository: "https://kubernetes-charts.storage.googleapis.com/"
  values:
    namespace: kube-system
    registry:
      disableScanning: true
