apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "System resources"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "kube-system"
      server: "*"
    - namespace: "metrics"
      server: "*"
    - namespace: "sealed-secrets"
      server: "*"
  sourceRepos:
    - "*"
