---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
metadata:
  name: "flux"
  namespace: "flux"
spec:
  helmVersion: "v3"
  releaseName: "flux"
  chart:
    repository: "https://charts.fluxcd.io"
    name: "flux"
    version: "1.4.0"
  values:
    sync:
      interval: "5m"
    git:
      url: "git@github.com:holtje/hive-config"
      branch: "main"
      path: "namespaces,releases,workloads"
      user: "Hive Queen"
      email: "docwhat@users.noreply.github.com"
    syncGarbageCollection:
      enabled: true
