---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
metadata:
  name: "helm-operator"
  namespace: "flux"
spec:
  helmVersion: "v3"
  releaseName: "helm-operator"
  chart:
    repository: "https://charts.fluxcd.io"
    name: "flux"
    version: "1.3.0"
  values:
    namespace: flux
    helm:
      versions: v3
    git:
      ssh:
        secretName: "flux-git-deploy"
