---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: traefik
  namespace: system
  labels:
    app.kubernetes.io/name: traefik
spec:
  helmVersion: v3
  targetNamespace: system
  releaseName: traefik
  chart:
    name: "traefik"
    repository: "https://containous.github.io/traefik-helm-chart"
    version: "2.2.1"
  values:
    rbac.enabled: false
    # https://www.linode.com/docs/kubernetes/deploy-nodebalancers-with-linode-ccm/#annotations
    "service.annotations.service\\.beta\\.kubernetes\\.io/linode-loadbalancer-protocol": "tcp"
