---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
  annotations:
    fluxcd.io/tag.demo-site: semver:~8.7
    fluxcd.io/automated: "true"

spec:
  helmVersion: v3
  targetNamespace: kube-system
  releaseName: traefik
  chart:
    name: traefik
    version: 8.7.1
    repository: https://containous.github.io/traefik-helm-chart/
  values:
    service:
      annotations:
        # https://www.linode.com/docs/kubernetes/deploy-nodebalancers-with-linode-ccm/#annotations
        "service.beta.kubernetes.io/linode-loadbalancer-protocol": "tcp"
    ingressRoute:
      dashboard:
        labels:
          "app.kubernetes.io/name": "traefik"
    env:
      - name: "LINODE_TOKEN"
        valueFrom:
          secretKeyRef:
            name: traefik-linode-dns
            key: token

    additionalArguments:
      - "--log.level=DEBUG"
      - "--certificatesresolvers.le.acme.email=docwhat@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.dnschallenge.provider=linodev4"
      - "--certificatesresolvers.le.acme.dnschallenge.delaybeforecheck=0"
      # - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    persistence:
      enabled: true
      size: 1Gi
      annotations:
        "pv.beta.kubernetes.io/gid": "65532"
      podSecurityContext:
        fsGroup: 65532
