---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-import
  namespace: docwhat
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.go-import: "semver:~1"
spec:
  selector:
    matchLabels:
      app: go-import
      environment: production
  template:
    metadata:
      labels:
        app: go-import
        environment: production
    spec:
      containers:
        - name: go-import
          image: docker.io/docwhat/go-importd:v1.1.0
          resources:
            requests:
              memory: "10Mi"
          env:
            - name: "GO_IMPORTD_GITHUB_USER_URL"
              value: "https://github.com/docwhat"
            - name: "GO_IMPORTD_IMPORT_DOMAIN"
              value: "docwhat.org"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          readinessProbe:
            periodSeconds: 60
            timeoutSeconds: 2
            httpGet:
              path: "/go-importd?go-get=1"
              port: 80
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: go-import
  namespace: docwhat
  labels:
    app: go-import
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-import
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 100
---
apiVersion: v1
kind: Service
metadata:
  name: go-import
  namespace: docwhat
  labels:
    app: go-import
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: go-import
    environment: production
