---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: private-calendar-chart
  namespace: docwhat
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: "glob:sha-*"

spec:
  helmVersion: v3
  targetNamespace: docwhat
  releaseName: private-calendar
  chart:
    git: "git@github.com:holtje/hive-config.git"
    ref: "main"
    path: "charts/vacation-calendar"
    secretName: "flux-git-deploy"
  values:
    image:
      repository: "docker.pkg.github.com/docwhat/vacation-calendar/vacation-calendar"
      tag: "sha-154489e"
    imagePullSecrets:
      - name: github-docker-secret
    resources:
      requests:
        cpu: "2m"

    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
