---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-cleaning
  namespace: docwhat
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: street-cleaning
      environment: production
  template:
    metadata:
      labels:
        app: street-cleaning
        environment: production
    spec:
      containers:
        - name: street-cleaning
          image: docker.io/docwhat/street_cleaning:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.5m"
              memory: "8Mi"
            limits:
              memory: "32Mi"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /run
              name: run-volume
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: street-cleaning
  namespace: docwhat
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: street-cleaning
    environment: production
