---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacation-calendar
  namespace: docwhat
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vacation-calendar
      environment: production
  template:
    metadata:
      labels:
        app: vacation-calendar
        environment: production
    spec:
      containers:
        - name: vacation-calendar
          image: docker.io/docwhat/work-calendar:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "20m"
              memory: "16Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /run
              name: run-volume
          securityContext:
            readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: dockerio-secret
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: run-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vacation-calendar
  namespace: docwhat
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: vacation-calendar
    environment: production
