---
apiVersion: "helm.fluxcd.io/v1"
kind: "HelmRelease"
# https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/release-configuration/
metadata:
  name: "prometheus-operator-chart"
  namespace: "monitoring"
spec:
  helmVersion: "v3"
  targetNamespace: "monitoring"
  releaseName: "prometheus-operator"
  chart:
    name: "prometheus-operator"
    version: "0.31.0"
    repository: "https://charts.bitnami.com/bitnami"
  values:
    image:
      pullSecrets:
        - dockerio-secret
    configmapReload:
      image:
        pullSecrets:
          - dockerio-secret
    kubeProxy:
      # Linode doesn't export any ports.
      enabled: false
    prometheus:
      externalUrl: "https://prometheus.docwhat.net/"
      image:
        pullSecrets:
          - dockerio-secret
      thanos:
        image:
          pullSecrets:
            - dockerio-secret
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: linode-block-storage
            resources:
              requests:
                storage: 10Gi
    alertmanager:
      externalUrl: https://alertmanager.docwhat.net/
      image:
        pullSecrets:
          - dockerio-secret
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: linode-block-storage
            resources:
              requests:
                storage: 10Gi
    # defaultRules:
    #   rules:
    #     general: false
    # # Can't monitor linode control plane.
    # kubeControllerManager:
    #   enabled: false
    # kubeScheduler:
    #   enabled: false
    # kubeEtcd:
    #   enabled: false
    # grafana:
    #   persistence:
    #     enabled: true
    #     existingClaim: grafana-claim
    #   admin:
    #     existingSecret: "grafana-env-secrets"
    #     userKey: "GF_SECURITY_ADMIN_USER"
    #     passwordKey: "GF_SECURITY_ADMIN_PASSWORD"
    #   plugins:
    #     - grafana-piechart-panel
    #   env:
    #     GF_AUTH_ANONYMOUS_ENABLED: false
    #     GF_AUTH_BASIC_ENABLED: false
    #     GF_AUTH_DISABLE_LOGIN_FORM: false
    #     GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: holtje
    #     GF_AUTH_GITHUB_ENABLED: true
    #     GF_AUTH_OAUTH_AUTO_LOGIN: false
    #     GF_SERVER_ROOT_URL: "https://grafana.docwhat.net/"
    #     GF_SERVER_ENABLE_GZIP: true
    #   envFromSecret: "grafana-env-secrets"
    # prometheusOperator:
    #   cleanupCustomResource: true
    # prometheus:
    #   prometheusSpec:
    #     externalUrl: "https://prometheus.docwhat.net/"
    #     storageSpec:
    #       volumeClaimTemplate:
    #         spec:
    #           storageClassName: linode-block-storage
    #           resources:
    #             requests:
    #               storage: 10Gi
    # alertmanager:
    #   alertmanagerSpec:
    #     externalUrl: https://alertmanager.docwhat.net/
    #     storage:
    #       volumeClaimTemplate:
    #         spec:
    #           storageClassName: linode-block-storage
    #           resources:
    #             requests:
    #               storage: 10Gi
