name: "Traefik docker image"

on:
  push:
    branches:
      - master
    paths:
      - "containers/traefik/**"
      - ".github/workflows/traefik-docker-image.yaml"
  schedule:
    # https://crontab.guru/#23_4_*_*_0
    # “At 04:23 on Sunday.”
    - cron: "23 4 * * 0"

jobs:
  traefik-docker-image:
    name: "Build & push image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: containers/traefik
          build_args: TRAEFIK_VERSION=2.2.4
          repository: docwhat/traefik
          tags: latest
          add_git_labels: true
