name: validation

on: [push, pull_request]

jobs:
  hrval:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Validate Helm Releases
        uses: stefanprodan/hrval-action@v3.2.0
        with:
          helmVersion: v3
          helmRelease: releases/
          kubernetesVersion: 1.17.0
      - name: Validate K8S Yaml
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@1.0.0
        with:
          files: namespaces,workloads
