---
name: versions

# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  schedule:
    - cron: "43 * * * *"
  push: {}

jobs:
  versions:
    # Name the Job
    name: Update Versions
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.3

      - name: GHCR Updates
        uses: mikefarah/yq@v3
        with:
          cmd: "apk add --no-cache curl jq bash && ./script/update-image-from-ghcr.bash"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          add: "docwhat-manifests/blog-staging.yaml"
          author_name: "Hive Queen"
          author_email: "docwhat+hivequeen@users.noreply.github.com"
          message: "chore: 🤖 version upgrade"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# EOF
