---
name: versions

# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  push:
    paths:
      - ".github/workflows/versions.yaml"
      - "script/update-image-from-ghcr.bash"
      - "script/get-latest-tag.jq"
  schedule:
    - cron: "43 23 * * 0"
  workflow_dispatch: {}

permissions: read-all

jobs:
  versions:
    # Name the Job
    name: Update versions
    # Set the agent to run on
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Install packages
        run: |
          sudo apt-get install -y curl jq bash &&
          sudo curl -sSfL -o /usr/bin/yq "https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}" &&
          sudo chmod +x /usr/bin/yq
        env:
          VERSION: v4.2.0
          BINARY: yq_linux_amd64

      - name: Update images
        run: "bash -x ./script/update-image-from-ghcr.bash"

      - name: Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "docwhat-manifests/blog-staging.yaml"
          author_name: "🐝 Hive Queen"
          author_email: "docwhat+hivequeen@users.noreply.github.com"
          message: "chore: 🤖 version upgrade"
# EOF
